"""auto-vote

Revision ID: 0a29c0a34373
Revises: 075ae17ff891
Create Date: 2023-03-17 18:49:37.802787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a29c0a34373'
down_revision = '075ae17ff891'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['postsv2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('postsv2', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('postsv2', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint('post_user_fk', 'postsv2', type_='foreignkey')
    op.create_foreign_key(None, 'postsv2', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('postsv2', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postsv2', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'postsv2', type_='foreignkey')
    op.create_foreign_key('post_user_fk', 'postsv2', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('postsv2', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('postsv2', 'user_id')
    op.drop_table('votes')
    # ### end Alembic commands ###
